include(
    "core",
    "compiler",
    "feature-manager",
    "feature-manager-singleton",
    "feature-manager-test",
    "converter-jackson",
    "converter-gson",
    "datasource-agconnect",
    "datasource-firebase",
    "datasource-remote",
    "datasource-debug",
    "test",
    "sample"
)
