name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-results
          path: |
            **/build/test-results/*
            **/build/reports/*
